<?php
session_start();
$page = 'pages/my_doc_medical_records';
require_once '../config/Database.php';
require_once '../classes/medical/MedicalRecord.php'; // adjust path if needed
require_once '../includes/header.php';
require_once '../includes/sidebar_user.php';

if (!isset($_SESSION['user_type']) || $_SESSION['user_type'] !== 'doctor') {
    echo "<div class='alert alert-danger text-center m-4'>Access denied. Doctors only.</div>";
    require_once '../includes/footer.php';
    exit();
}

$database = new Database();
$db = $database->connect();
$medrec = new MedicalRecord($db);
$doc_id = $_SESSION['profile_id'] ?? null;

if (!$doc_id) {
    echo "<div class='alert alert-warning text-center m-4'>Doctor information missing in session.</div>";
    require_once '../includes/footer.php';
    exit();
}
?>
<body class="account-page">
<div class="main-content p-4">
    <div class="container">

        <!-- HEADER CARD -->
        <div class="card shadow-sm border-0 rounded-4 mb-4 bg-teal text-white">
            <div class="card-body d-flex justify-content-between align-items-center">
                <div>
                    <h3 class="fw-bold mb-1">Medical Records</h3>
                    <p class="mb-0">Add, view and update medical records linked to appointments</p>
                </div>
                <i class="fas fa-notes-medical fa-3x opacity-75"></i>
            </div>
        </div>

        <!-- Tabs + Add button -->
                <!-- Tabs + Add button inside white card -->
        <div class="card shadow-sm border-0 rounded-4 mb-3">
            <div class="card-body bg-white rounded-4 p-3">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <button class="btn btn-teal btn-sm" onclick="openAddModal()">
                        <i class="fas fa-plus-circle"></i> Add Record
                    </button>
                </div>

                <!-- ✅ Search bar -->
                <div class="mb-3">
                    <div class="input-group">
                        <input type="text" class="form-control" id="searchPatientInput" placeholder="Search records by patient name or ID...">
                        <button class="btn btn-outline-secondary" type="button" id="searchPatientBtn">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>

                <!-- Tab content -->
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="my-records">
                        <div class="table-responsive">
                            <table class="table table-hover align-middle mb-0" id="recordsTable">
                                <thead>
                                    <tr>
                                        <th>Patient</th>
                                        <th>Appointment</th>
                                        <th>Visit Date</th>
                                        <th>Diagnosis</th>
                                        <th>Prescription</th>
                                        <th class="text-end">Actions</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>

                        <nav aria-label="Medical records pagination">
                            <ul class="pagination justify-content-center mt-3" id="records-pagination">
                                <!-- Pagination generated by JS -->
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- ADD / EDIT MODAL (SweetAlert is used; this is a fallback non-modal form used by JS) -->
<!-- We'll use SweetAlert for add/edit forms; no native bootstrap modal required. -->
<script src="../public/js/management.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', () => {
    loadRecords();

    document.getElementById('searchPatientBtn').addEventListener('click', searchMedicalRecords);
    document.getElementById('searchPatientInput').addEventListener('keypress', e => {
        if (e.key === 'Enter') searchMedicalRecords();
    });
    document.getElementById('searchPatientInput').addEventListener('input', function() {
        if (this.value.trim() === '') loadRecords();
    });
});

const apiBase = '../handlers/medical/medical_record_handler.php';
document.addEventListener('DOMContentLoaded', () => {
    loadRecords();
});

function loadRecords() {
    fetch(`${apiBase}?action=get_all`)
        .then(res => res.json())
        .then(res => {
            const tbody = document.querySelector('#recordsTable tbody');
            tbody.innerHTML = '';

            if (res.status === 'success' && res.data.length) {
                res.data.forEach(r => {
                    tbody.innerHTML += `
                        <tr>
                            <td><strong>${escapeHtml(r.patient_name)}</strong></td>
                            <td><span class="badge pastel-green">${formatDateTime(r.appt_date)}</span></td>
                            <td>${formatDate(r.med_rec_visit_date)}</td>
                            <td>${escapeHtml(shorten(r.med_rec_diagnosis, 60))}</td>
                            <td>${escapeHtml(shorten(r.med_rec_prescription, 60))}</td>
                            <td class="text-end">
                                <div class="btn-group btn-group-sm">
                                    <button class="btn btn-outline-info me-1" onclick="viewRecord(${r.med_rec_id})" title="View">
                                        <i class="fas fa-eye"></i>
                                    </button>
                                    <button class="btn btn-outline-primary me-1" onclick="openEditModal(${r.med_rec_id})" title="Edit">
                                        <i class="fas fa-edit"></i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    `;
                });

                // ✅ Initialize pagination after table rows are rendered
                initializePagination('recordsTable', 'records-pagination', 10);

            } else {
                tbody.innerHTML = `
                    <tr>
                        <td colspan="6" class="text-center text-muted py-3">
                            No medical records found.
                        </td>
                    </tr>`;
                document.getElementById('records-pagination').innerHTML = ''; // clear pagination if none
            }
        })
        .catch(err => {
            console.error(err);
            Swal.fire('Error', 'Failed to load medical records', 'error');
        });
}


// Helper: escape HTML to avoid injection in table display
function escapeHtml(str) {
    if (!str && str !== 0) return '';
    return String(str)
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&#39;');
}

function shorten(text, n) {
    if (!text) return '';
    return text.length > n ? text.slice(0,n-1) + '…' : text;}

function formatDate(d) {
    if (!d) return '';
    const dt = new Date(d);
    return dt.toLocaleDateString();
}
function formatDateTime(d) {
    if (!d) return '';
    const dt = new Date(d);
    return dt.toLocaleDateString() + ' • ' + dt.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});
}

// Open Add modal (SweetAlert form)
function openAddModal() {
    // first fetch appointments for this doctor to populate select
    fetch(`${apiBase}?action=get_appts`)
        .then(res => res.json())
        .then(res => {
            const appts = (res.status === 'success' && res.data) ? res.data : [];
            if (appts.length === 0) {
                return Swal.fire('No appointments', 'You have no appointments to attach a medical record to.', 'info');
            }

            // build appointment options (value=appt_id)
            const optionsHtml = appts.map(a => `<option value="${a.appt_id}">${escapeHtml(a.patient_name)} — ${formatDateTime(a.appt_date)}</option>`).join('');

            Swal.fire({
                title: 'Add Medical Record',
                html: `
                    <label class="form-label">Appointment</label>
                    <select id="mr_appt" class="form-select mb-2">${optionsHtml}</select>
                    <label class="form-label">Visit Date</label>
                    <input id="mr_visit" type="date" class="form-control mb-2" value="<?= date('Y-m-d'); ?>">
                    <label class="form-label">Diagnosis</label>
                    <textarea id="mr_diag" class="form-control mb-2" rows="3"></textarea>
                    <label class="form-label">Prescription</label>
                    <textarea id="mr_presc" class="form-control" rows="2"></textarea>
                `,
                showCancelButton: true,
                confirmButtonText: 'Save',
                preConfirm: () => {
                    return {
                        appt_id: document.getElementById('mr_appt').value,
                        med_rec_visit_date: document.getElementById('mr_visit').value,
                        med_rec_diagnosis: document.getElementById('mr_diag').value.trim(),
                        med_rec_prescription: document.getElementById('mr_presc').value.trim()
                    };
                }
            }).then(result => {
                if (!result.isConfirmed) return;
                const payload = result.value;
                if (!payload.appt_id || !payload.med_rec_visit_date || !payload.med_rec_diagnosis) {
                    return Swal.fire('Error','Please fill required fields (Appointment, Visit Date, Diagnosis)','error');
                }
                fetch(`${apiBase}?action=add`, {
                    method: 'POST',
                    headers: {'Content-Type':'application/json'},
                    body: JSON.stringify(payload)
                })
                .then(r => r.json())
                .then(res => {
                    if (res.status === 'success') {
                        Swal.fire('Saved',res.message,'success');
                        loadRecords();
                    } else {
                        Swal.fire('Error',res.message || 'Failed to save','error');
                    }
                })
                .catch(() => Swal.fire('Error','Network error','error'));
            });
        });
}

// Open edit modal
function openEditModal(med_rec_id) {
    fetch(`${apiBase}?action=get&med_rec_id=${med_rec_id}`)
        .then(r => r.json())
        .then(res => {
            if (res.status !== 'success' || !res.data) {
                return Swal.fire('Error', res.message || 'Record not found', 'error');
            }
            const rdata = res.data;

            // load appts list too, but set selected appt
            fetch(`${apiBase}?action=get_appts`)
                .then(r2 => r2.json())
                .then(res2 => {
                    const appts = (res2.status === 'success' && res2.data) ? res2.data : [];
                    const optionsHtml = appts.map(a => `<option value="${a.appt_id}" ${a.appt_id == rdata.appt_id ? 'selected' : ''}>${escapeHtml(a.patient_name)} — ${formatDateTime(a.appt_date)}</option>`).join('');

                    Swal.fire({
                        title: 'Edit Medical Record',
                        html: `
                            <label class="form-label">Appointment</label>
                            <select id="mr_appt" class="form-select mb-2">${optionsHtml}</select>
                            <label class="form-label">Visit Date</label>
                            <input id="mr_visit" type="date" class="form-control mb-2" value="${rdata.med_rec_visit_date ? rdata.med_rec_visit_date.split(' ')[0] : '<?= date('Y-m-d'); ?>'}">
                            <label class="form-label">Diagnosis</label>
                            <textarea id="mr_diag" class="form-control mb-2" rows="3">${escapeHtml(rdata.med_rec_diagnosis)}</textarea>
                            <label class="form-label">Prescription</label>
                            <textarea id="mr_presc" class="form-control" rows="2">${escapeHtml(rdata.med_rec_prescription)}</textarea>
                        `,
                        showCancelButton: true,
                        confirmButtonText: 'Update',
                        preConfirm: () => ({
                            med_rec_id: med_rec_id,
                            appt_id: document.getElementById('mr_appt').value,
                            med_rec_visit_date: document.getElementById('mr_visit').value,
                            med_rec_diagnosis: document.getElementById('mr_diag').value.trim(),
                            med_rec_prescription: document.getElementById('mr_presc').value.trim()
                        })
                    }).then(result => {
                        if (!result.isConfirmed) return;
                        const payload = result.value;
                        if (!payload.appt_id || !payload.med_rec_visit_date || !payload.med_rec_diagnosis) {
                            return Swal.fire('Error','Please fill required fields','error');
                        }
                        fetch(`${apiBase}?action=update`, {
                            method: 'POST',
                            headers: {'Content-Type':'application/json'},
                            body: JSON.stringify(payload)
                        })
                        .then(r => r.json())
                        .then(res => {
                            if (res.status === 'success') {
                                Swal.fire('Updated', res.message, 'success');
                                loadRecords();
                            } else {
                                Swal.fire('Error', res.message || 'Failed to update', 'error');
                            }
                        })
                        .catch(() => Swal.fire('Error','Network error','error'));
                    });
                });
        });
}

// View record details
function viewRecord(med_rec_id) {
    fetch(`${apiBase}?action=get&med_rec_id=${med_rec_id}`)
        .then(r => r.json())
        .then(res => {
            if (res.status !== 'success' || !res.data) {
                return Swal.fire('Error', res.message || 'Record not found', 'error');
            }
            const d = res.data;
            Swal.fire({
                title: 'Medical Record Details',
                html: `
                    <div class="text-start">
                        <p><strong>Patient:</strong> ${escapeHtml(d.patient_name)}</p>
                        <p><strong>Appointment:</strong> ${formatDateTime(d.appt_date)}</p>
                        <p><strong>Visit Date:</strong> ${formatDate(d.med_rec_visit_date)}</p>
                        <p><strong>Diagnosis:</strong><br>${escapeHtml(d.med_rec_diagnosis)}</p>
                        <p><strong>Prescription:</strong><br>${escapeHtml(d.med_rec_prescription)}</p>
                    </div>
                `,
                width: 600,
                confirmButtonText: 'Close'
            });
        });
}

// Delete record
function deleteRecord(med_rec_id) {
    Swal.fire({
        title: 'Delete medical record?',
        text: "This action cannot be undone.",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonText: 'Delete',
        confirmButtonColor: '#d33'
    }).then(result => {
        if (result.isConfirmed) {
            fetch(`${apiBase}?action=delete`, {
                method: 'POST',
                headers: {'Content-Type':'application/json'},
                body: JSON.stringify({ med_rec_id })
            })
            .then(r => r.json())
            .then(res => {
                if (res.status === 'success') {
                    Swal.fire('Deleted', res.message, 'success');
                    loadRecords();
                } else {
                    Swal.fire('Error', res.message || 'Could not delete', 'error');
                }
            })
            .catch(() => Swal.fire('Error','Network error','error'));
        }
    });
}

// Add these event listeners after DOMContentLoaded
document.addEventListener('DOMContentLoaded', () => {
    loadRecords();
    
    // Add event listeners for search
    document.getElementById('searchPatientBtn').addEventListener('click', searchMedicalRecords);
    document.getElementById('searchPatientInput').addEventListener('keypress', e => {
        if (e.key === 'Enter') searchMedicalRecords();
    });

     // Add real-time clear detection
    document.getElementById('searchPatientInput').addEventListener('input', function() {
        if (this.value.trim() === '') {
            loadRecords();
        }
    });
});

function searchMedicalRecords() {
    const input = document.getElementById('searchPatientInput').value.trim();
    const tbody = document.querySelector('#recordsTable tbody');

    if (!input) {
        loadRecords(); // Empty search resets to full list
        return;
    }

    fetch(`${apiBase}?action=search_by_name&name=${encodeURIComponent(input)}`)
        .then(res => {
            if (!res.ok) throw new Error('Network response was not ok');
            return res.json();
        })
        .then(data => {
            tbody.innerHTML = '';

            if (data.status === 'success' && data.data && data.data.length > 0) {
                data.data.forEach(r => {
                    tbody.innerHTML += `
                        <tr>
                            <td><strong>${escapeHtml(r.patient_name)}</strong></td>
                            <td><span class="badge pastel-green">${formatDateTime(r.appt_date)}</span></td>
                            <td>${formatDate(r.med_rec_visit_date)}</td>
                            <td>${escapeHtml(shorten(r.med_rec_diagnosis, 60))}</td>
                            <td>${escapeHtml(shorten(r.med_rec_prescription, 60))}</td>
                            <td class="text-end">
                                <div class="btn-group btn-group-sm">
                                    <button class="btn btn-outline-info" onclick="viewRecord(${r.med_rec_id})" title="View">
                                        <i class="fas fa-eye"></i>
                                    </button>
                                    <button class="btn btn-outline-primary" onclick="openEditModal(${r.med_rec_id})" title="Edit">
                                        <i class="fas fa-edit"></i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    `;
                });

                // ✅ Apply reinitialized pagination for search results
                const visibleRows = Array.from(document.querySelectorAll('#recordsTable tbody tr'));
                reinitializePaginationAfterSearch('recordsTable', 'records-pagination', visibleRows);

            } else {
                tbody.innerHTML = `
                    <tr>
                        <td colspan="6" class="text-center text-muted py-3">
                            ${data.message || 'No records found for that patient name.'}
                        </td>
                    </tr>`;
                document.getElementById('records-pagination').innerHTML = ''; // clear pagination
            }
        })
        .catch(err => {
            console.error('Search error:', err);
            Swal.fire('Error', 'Failed to search records: ' + err.message, 'error');
        });
}


</script>

<?php require_once '../includes/footer.php'; ?>